topics_gpt =['The evolution of artificial satellites and their impact on communication.',
 'The history of the Internet of Things (IoT) and smart devices.',
 'The rise of cryptocurrency and blockchain technology.',
 'The development and impact of 3D printing technology.',
 'The discovery and exploration of Pluto.',
 'The history of quantum computing and its future potential.',
 'The impact of the Human Genome Project on medicine.',
 'The invention of the microwave oven and its impact on society.',
 'The story of the Hubble Space Telescope and its discoveries.',
 'The development of virtual reality and its applications.',
 'The history and effects of the global financial crisis of 2008.',
 'The story of electric vehicles and their rise in the 21st century.',
 'The impact of climate change on the polar ice caps.',
 'The history of the World Health Organization and global health initiatives.',
 'The invention and evolution of the camera and photography.',
 'The story of the discovery of insulin and its impact on diabetes treatment.',
 'The development of social networking sites and their impact on society.',
 'The history of the Nobel Prize and its laureates.',
 'The invention of the telescope and its impact on astronomy.',
 'The story of the International Space Station and international collaboration in space.',
 'The development and impact of wireless technology.',
 'The history of the conservation movement and national parks.',
 'The story of the discovery and use of X-rays in medicine.',
 'The rise of the gig economy and its impact on traditional employment.',
 'The development of antibiotics and the fight against bacterial infections.',
 'The history of the atomic bomb and the nuclear age.',
 'The invention of the jet engine and its impact on air travel.',
 'The story of the discovery of the Americas by European explorers.',
 'The history and cultural impact of jazz music.',
 'The development of the modern computer operating system.',
 'The story of the eradication of the Guinea worm disease.',
 'The history of the Mars rovers and their exploration of the Red Planet.',
 'The development and implications of gene editing technologies.',
 'The rise of online education and its impact on traditional learning.',
 'The invention of the transistor and the birth of modern electronics.',
 'The story of the discovery of the Titanic wreck.',
 'The impact of mega-corporations on global economy and culture.',
 'The development of drone technology and its applications.',
 'The history of the Silk Road and its impact on ancient trade.',
 'The story of the renewable energy transition and its challenges.',
 'The invention of GPS technology and its global impact.',
 'The development of the Braille system and its impact on the visually impaired.',
 'The history of the feminist movement and its achievements.',
 'The story of the discovery of antibiotics and their impact on medicine.',
 'The development of the video game industry and its cultural impact.',
 'The history of the civil rights movement and its legacy.',
 'The story of the construction of the Burj Khalifa and modern engineering marvels.',
 'The development of the digital camera and the impact on photography.',
 'The history of the green revolution and its impact on agriculture.',
 'The story of the discovery and exploration of the Great Barrier Reef.']